<a href="https://colab.research.google.com/github/yangjunmo37/-2-Deeplearning_with_tensorflow/blob/3%EC%9E%A5/3_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K-최근접 이웃

주어진 데이터 분류,
주변 k개의 데이터를 연결하면서 분류한다.

---



라이브러리 호출 및 데이터 준비

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics

names = ['sepal-length','sepal-width', 'petal-length', 'petal-width', 'Class']

dataset = pd.read_csv('/content/gdrive/MyDrive/딥러닝 텐서플로 교과서/chap3/data/iris.data', names=names)

훈련과 테스트 데이터셋 분리

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
X_train[:10]

array([[6.5, 3.2, 5.1, 2. ],
       [5.9, 3.2, 4.8, 1.8],
       [4.6, 3.2, 1.4, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.1, 2.9, 4.7, 1.4],
       [6.6, 2.9, 4.6, 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.9, 3.1, 5.1, 2.3]])

In [ ]:
s = StandardScaler()
# 평균이 0, 표준편차 1로 변환
X_train = s.fit_transform(X_train)
X_test = s.fit_transform(X_test)
X_train[:10]

array([[ 0.7795133 ,  0.30289852,  0.74653469,  1.01348212],
       [ 0.05250608,  0.30289852,  0.57557255,  0.75499571],
       [-1.52267624,  0.30289852, -1.36199841, -1.31289554],
       [-1.76501198,  0.30289852, -1.41898579, -1.31289554],
       [-0.91683689,  1.02504068, -1.36199841, -1.31289554],
       [-0.18982966,  3.19146717, -1.30501103, -1.05440913],
       [ 0.29484182, -0.41924364,  0.51858517,  0.2380229 ],
       [ 0.90068117, -0.41924364,  0.46159779,  0.1087797 ],
       [-0.4321654 , -1.14138581,  0.34762303, -0.02046351],
       [ 1.26418478,  0.06218446,  0.74653469,  1.40121173]])

모델 생성 및 훈련

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=50)
# k가 50
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=50)

모델 정확도

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
y_pred = knn.predict(X_test)

In [ ]:
print('정확도:', accuracy_score(y_test, y_pred))

정확도: 0.9333333333333333


최적의 K 찾기

In [ ]:
k = 10
acc_array = np.zeros(k)
acc_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
for k in np.arange(1, k+1, 1):
    classifier = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    acc_array[k-1] = acc

In [ ]:
max_acc = np.amax(acc_array)
max_acc

1.0

In [ ]:
acc_list = list(acc_array)
acc_list

[1.0, 0.9666666666666667, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [ ]:
k = acc_list.index(max_acc)

In [ ]:
print(f'정확도가 {max_acc}으로 최적의 k는 {k+1}입니다. ')

정확도가 1.0으로 최적의 k는 1입니다. 
